### ISSUE TITLE
Redundancy Analysis

### ISSUE THREAD

**Issue by mm4907** [jpuritz/BIO_594_2023#11]
I am getting this error when trying to do the second step of the redundancy analysis:

> coords = read.csv("coordinates.csv")
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'coordinates.csv': No such file or directory

Any help would be appreciated!

**Comment by pdimens** [comment]
See #8 because it's likely the same thing.

1. Try using the full path to the coordinates.csv file
2. Double check what your R/Studio session's working/project directory is

**Comment by mm4907** [comment]
It worked out, thanks!
